<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../tests.targets" />

  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" Version="1.61.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tests.Integration\Tests.Integration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
