// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoyalIdentity.UserAccounts.Sqlite;

#nullable disable

namespace RoyalIdentity.UserAccounts.Sqlite.Migrations
{
    [DbContext(typeof(UserAccountsSqliteDbContext))]
    [Migration("20260721010154_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.Accounts.Domain.PasswordHistoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBySubjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RealmId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UserAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("RealmId", "UserAccountId", "CreatedAt");

                    b.ToTable("UserAccountPasswordHistory", (string)null);
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RealmId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SessionsValidAfter")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RealmId", "ExternalId");

                    b.HasIndex("RealmId", "NormalizedUsername")
                        .IsUnique();

                    b.HasIndex("RealmId", "SubjectId")
                        .IsUnique();

                    b.ToTable("UserAccounts", (string)null);
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccountActionToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsumedIpHash")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedIpHash")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RealmId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UserAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgentHash")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("RealmId", "TokenHash")
                        .IsUnique();

                    b.HasIndex("RealmId", "UserAccountId", "Purpose");

                    b.ToTable("UserAccountActionTokens", (string)null);
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccountCredential", b =>
                {
                    b.Property<long>("UserAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedPasswordAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastPasswordFailureAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LockoutEndAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("PasswordChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("RealmId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserAccountId");

                    b.HasIndex("RealmId", "UserAccountId");

                    b.ToTable("UserAccountCredentials", (string)null);
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccountEmail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFictitious")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RealmId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UserAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("RealmId", "NormalizedAddress");

                    b.HasIndex("RealmId", "UserAccountId")
                        .IsUnique()
                        .HasDatabaseName("UX_UserAccountEmails_PrimaryPerAccount")
                        .HasFilter("\"IsPrimary\" = 1");

                    b.HasIndex("RealmId", "UserAccountId", "NormalizedAddress")
                        .IsUnique();

                    b.ToTable("UserAccountEmails", (string)null);
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccountPhone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RealmId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UserAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("RealmId", "NormalizedNumber");

                    b.HasIndex("RealmId", "UserAccountId")
                        .IsUnique()
                        .HasDatabaseName("UX_UserAccountPhones_PrimaryPerAccount")
                        .HasFilter("\"IsPrimary\" = 1");

                    b.HasIndex("RealmId", "UserAccountId", "NormalizedNumber")
                        .IsUnique();

                    b.ToTable("UserAccountPhones", (string)null);
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccountRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RealmId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UserAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("RealmId", "NormalizedName");

                    b.HasIndex("RealmId", "UserAccountId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("UserAccountRoles", (string)null);
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.ScopeProperties.Domain.PropertyDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PropertyScopeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RealmId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertyScopeId");

                    b.HasIndex("RealmId", "ClaimType")
                        .IsUnique();

                    b.HasIndex("RealmId", "PropertyScopeId");

                    b.ToTable("PropertyDefinitions", (string)null);
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.ScopeProperties.Domain.PropertyDefinitionVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Help")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCollection")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PropertyDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PropertyScopeVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RealmId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationRules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertyDefinitionId");

                    b.HasIndex("PropertyScopeVersionId", "PropertyDefinitionId")
                        .IsUnique();

                    b.HasIndex("RealmId", "PropertyDefinitionId");

                    b.ToTable("PropertyDefinitionVersions", (string)null);
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.ScopeProperties.Domain.PropertyScope", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActiveVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RealmId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActiveVersionId");

                    b.HasIndex("RealmId", "Name")
                        .IsUnique();

                    b.ToTable("PropertyScopes", (string)null);
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.ScopeProperties.Domain.PropertyScopeVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<long>("PropertyScopeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RealmId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PropertyScopeId");

                    b.HasIndex("RealmId", "PropertyScopeId", "Status");

                    b.HasIndex("RealmId", "PropertyScopeId", "Version")
                        .IsUnique();

                    b.ToTable("PropertyScopeVersions", (string)null);
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.ScopeProperties.Domain.UserAccountPropertyValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PropertyDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RealmId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UserAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertyDefinitionId");

                    b.HasIndex("RealmId", "ClaimType");

                    b.HasIndex("RealmId", "UserAccountId", "ClaimType");

                    b.HasIndex("UserAccountId", "PropertyDefinitionId", "Ordinal")
                        .IsUnique();

                    b.ToTable("UserAccountPropertyValues", (string)null);
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.Accounts.Domain.PasswordHistoryEntry", b =>
                {
                    b.HasOne("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccount", "UserAccount")
                        .WithMany("PasswordHistoryItems")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccount", b =>
                {
                    b.OwnsOne("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccountBlockState", "BlockState", b1 =>
                        {
                            b1.Property<long>("UserAccountId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTimeOffset?>("BlockedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("BlockedAt");

                            b1.Property<string>("BlockedReason")
                                .HasColumnType("TEXT")
                                .HasColumnName("BlockedReason");

                            b1.Property<DateTimeOffset?>("EndsAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("BlockEndsAt");

                            b1.Property<bool>("IsBlocked")
                                .HasColumnType("INTEGER")
                                .HasColumnName("IsBlocked");

                            b1.Property<DateTimeOffset?>("StartsAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("BlockStartsAt");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("UserAccounts");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.Navigation("BlockState")
                        .IsRequired();
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccountActionToken", b =>
                {
                    b.HasOne("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccountCredential", b =>
                {
                    b.HasOne("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccount", "UserAccount")
                        .WithOne("LocalCredential")
                        .HasForeignKey("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccountCredential", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccountEmail", b =>
                {
                    b.HasOne("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccount", "UserAccount")
                        .WithMany("EmailItems")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccountPhone", b =>
                {
                    b.HasOne("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccount", "UserAccount")
                        .WithMany("PhoneItems")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccountRole", b =>
                {
                    b.HasOne("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccount", "UserAccount")
                        .WithMany("RoleItems")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.ScopeProperties.Domain.PropertyDefinition", b =>
                {
                    b.HasOne("RoyalIdentity.UserAccounts.Features.ScopeProperties.Domain.PropertyScope", "PropertyScope")
                        .WithMany("DefinitionItems")
                        .HasForeignKey("PropertyScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyScope");
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.ScopeProperties.Domain.PropertyDefinitionVersion", b =>
                {
                    b.HasOne("RoyalIdentity.UserAccounts.Features.ScopeProperties.Domain.PropertyDefinition", "PropertyDefinition")
                        .WithMany()
                        .HasForeignKey("PropertyDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoyalIdentity.UserAccounts.Features.ScopeProperties.Domain.PropertyScopeVersion", "PropertyScopeVersion")
                        .WithMany("DefinitionVersionItems")
                        .HasForeignKey("PropertyScopeVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyDefinition");

                    b.Navigation("PropertyScopeVersion");
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.ScopeProperties.Domain.PropertyScopeVersion", b =>
                {
                    b.HasOne("RoyalIdentity.UserAccounts.Features.ScopeProperties.Domain.PropertyScope", "PropertyScope")
                        .WithMany("VersionItems")
                        .HasForeignKey("PropertyScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyScope");
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.ScopeProperties.Domain.UserAccountPropertyValue", b =>
                {
                    b.HasOne("RoyalIdentity.UserAccounts.Features.ScopeProperties.Domain.PropertyDefinition", "PropertyDefinition")
                        .WithMany()
                        .HasForeignKey("PropertyDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccount", "UserAccount")
                        .WithMany("PropertyValueItems")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyDefinition");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.Accounts.Domain.UserAccount", b =>
                {
                    b.Navigation("EmailItems");

                    b.Navigation("LocalCredential")
                        .IsRequired();

                    b.Navigation("PasswordHistoryItems");

                    b.Navigation("PhoneItems");

                    b.Navigation("PropertyValueItems");

                    b.Navigation("RoleItems");
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.ScopeProperties.Domain.PropertyScope", b =>
                {
                    b.Navigation("DefinitionItems");

                    b.Navigation("VersionItems");
                });

            modelBuilder.Entity("RoyalIdentity.UserAccounts.Features.ScopeProperties.Domain.PropertyScopeVersion", b =>
                {
                    b.Navigation("DefinitionVersionItems");
                });
#pragma warning restore 612, 618
        }
    }
}
