using System.Buffers.Binary;
using System.Security.Cryptography;
using System.Text;

namespace RoyalIdentity.Storage.EntityFramework.Operational.Materialization;

/// <summary>
/// <para>
///     Computes the persisted form of a replay handle (plan-replay-protection DF4): the raw value — a
///     client-chosen <c>jti</c> — is never written to the database, not in the key and not in any column.
/// </para>
/// <para>
///     This is deliberately <b>not</b> <see cref="OperationalLookupDigest"/>. That type documents skipping HMAC
///     because the handles it covers are generated by this server with high entropy; a <c>jti</c> is chosen by
///     the client and may be a counter. The justification does not transfer, so it is not reused, and the
///     guarantee claimed here is narrower: the digest is pseudonymisation and domain separation, not
///     confidentiality (DF17). It is not assumed to resist a dictionary attack over predictable <c>jti</c>
///     values by someone who can already read the table. If that enters the threat model, swapping in a keyed
///     digest is a change confined to this type — with a version bump below, which simply retires the old rows
///     as unmatched.
/// </para>
/// <para>
///     Fields are length-prefixed rather than joined by a separator, so no combination of inputs can produce the
///     same digest as a different combination — including a handle containing whatever character a separator
///     would have used.
/// </para>
/// </summary>
public sealed class ReplayHandleDigest
{
    /// <summary>
    /// Version of the digest construction, mixed in as a field of its own. Changing it changes every digest, so
    /// existing rows stop matching and simply expire — which is the correct outcome: they protect artifacts that
    /// are themselves short-lived.
    /// </summary>
    public const int CurrentVersion = 1;

    /// <summary>Domain of this digest, keeping it disjoint from every other digest of the family.</summary>
    private const string Domain = OperationalRecordTypes.ReplayHandle;

    /// <summary>The digest of <paramref name="handle"/> within <paramref name="purpose"/>, as lowercase hex.</summary>
    /// <param name="purpose">The kind of artifact being protected.</param>
    /// <param name="handle">The raw handle. Never persisted, never logged.</param>
    public string Compute(string purpose, string handle)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(purpose);
        ArgumentException.ThrowIfNullOrEmpty(handle);

        using var hash = IncrementalHash.CreateHash(HashAlgorithmName.SHA256);

        AppendField(hash, CurrentVersion);
        AppendField(hash, Domain);
        AppendField(hash, purpose);
        AppendField(hash, handle);

        return Convert.ToHexStringLower(hash.GetHashAndReset());
    }

    private static void AppendField(IncrementalHash hash, int value)
    {
        Span<byte> buffer = stackalloc byte[sizeof(int)];
        // Fixed endianness: the digest is persisted, so it must not depend on the architecture that wrote it.
        BinaryPrimitives.WriteInt32LittleEndian(buffer, value);
        AppendField(hash, buffer);
    }

    private static void AppendField(IncrementalHash hash, string value)
        => AppendField(hash, Encoding.UTF8.GetBytes(value));

    private static void AppendField(IncrementalHash hash, ReadOnlySpan<byte> value)
    {
        Span<byte> length = stackalloc byte[sizeof(int)];
        BinaryPrimitives.WriteInt32LittleEndian(length, value.Length);

        hash.AppendData(length);
        hash.AppendData(value);
    }
}
