// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoyalIdentity.Storage.EntityFramework.Sqlite;

#nullable disable

namespace RoyalIdentity.Storage.EntityFramework.Sqlite.Migrations
{
    [DbContext(typeof(ConfigurationSqliteDbContext))]
    partial class ConfigurationSqliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("RoyalIdentity.Data.Configuration.Entities.ClientClaimEntity", b =>
                {
                    b.Property<string>("RealmId")
                        .HasColumnType("TEXT")
                        .HasColumnName("realm_id")
                        .UseCollation("BINARY");

                    b.Property<string>("ClientId")
                        .HasColumnType("TEXT")
                        .HasColumnName("client_id")
                        .UseCollation("BINARY");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<string>("Issuer")
                        .HasColumnType("TEXT")
                        .HasColumnName("issuer");

                    b.Property<string>("OriginalIssuer")
                        .HasColumnType("TEXT")
                        .HasColumnName("original_issuer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .HasColumnType("TEXT")
                        .HasColumnName("value_type");

                    b.HasKey("RealmId", "ClientId", "Ordinal");

                    b.ToTable("client_claims", (string)null);
                });

            modelBuilder.Entity("RoyalIdentity.Data.Configuration.Entities.ClientEntity", b =>
                {
                    b.Property<string>("RealmId")
                        .HasColumnType("TEXT")
                        .HasColumnName("realm_id")
                        .UseCollation("BINARY");

                    b.Property<string>("ClientId")
                        .HasColumnType("TEXT")
                        .HasColumnName("client_id")
                        .UseCollation("BINARY");

                    b.Property<int>("AbsoluteRefreshTokenLifetime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("absolute_refresh_token_lifetime");

                    b.Property<int>("AccessTokenLifetime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("access_token_lifetime");

                    b.Property<bool>("AllowAllResourceServers")
                        .HasColumnType("INTEGER")
                        .HasColumnName("allow_all_resource_servers");

                    b.Property<bool>("AllowLogoutWithoutUserConfirmation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("allow_logout_without_user_confirmation");

                    b.Property<bool>("AllowOfflineAccess")
                        .HasColumnType("INTEGER")
                        .HasColumnName("allow_offline_access");

                    b.Property<bool>("AllowPlainTextPkce")
                        .HasColumnType("INTEGER")
                        .HasColumnName("allow_plain_text_pkce");

                    b.Property<bool>("AllowRememberConsent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("allow_remember_consent");

                    b.Property<bool>("AlwaysIncludeUserClaimsInIdToken")
                        .HasColumnType("INTEGER")
                        .HasColumnName("always_include_user_claims_in_id_token");

                    b.Property<bool>("AlwaysSendClientClaims")
                        .HasColumnType("INTEGER")
                        .HasColumnName("always_send_client_claims");

                    b.Property<int>("AuthorizationCodeLifetime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("authorization_code_lifetime");

                    b.Property<bool>("BackChannelLogoutSessionRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("back_channel_logout_session_required");

                    b.Property<string>("ClientClaimsPrefix")
                        .HasColumnType("TEXT")
                        .HasColumnName("client_claims_prefix");

                    b.Property<int>("ClientType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("client_type");

                    b.Property<string>("ClientUri")
                        .HasColumnType("TEXT")
                        .HasColumnName("client_uri");

                    b.Property<int?>("ConsentLifetime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("consent_lifetime");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("EnableLocalLogin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enable_local_login");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<bool>("FrontChannelLogoutSessionRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("front_channel_logout_session_required");

                    b.Property<int>("IdentityTokenLifetime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("identity_token_lifetime");

                    b.Property<bool>("IncludeJwtId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("include_jwt_id");

                    b.Property<string>("LogoUri")
                        .HasColumnType("TEXT")
                        .HasColumnName("logo_uri");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ProtocolType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("protocol_type");

                    b.Property<int>("RefreshTokenExpiration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("refresh_token_expiration");

                    b.Property<long>("RefreshTokenPostConsumedTimeToleranceTicks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("refresh_token_post_consumed_time_tolerance_ticks");

                    b.Property<bool>("RequireClientSecret")
                        .HasColumnType("INTEGER")
                        .HasColumnName("require_client_secret");

                    b.Property<bool>("RequireConsent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("require_consent");

                    b.Property<bool>("RequirePkce")
                        .HasColumnType("INTEGER")
                        .HasColumnName("require_pkce");

                    b.Property<int>("SlidingRefreshTokenLifetime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sliding_refresh_token_lifetime");

                    b.Property<bool>("UpdateAccessTokenClaimsOnRefresh")
                        .HasColumnType("INTEGER")
                        .HasColumnName("update_access_token_claims_on_refresh");

                    b.Property<int?>("UserSsoLifetime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_sso_lifetime");

                    b.HasKey("RealmId", "ClientId");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("RoyalIdentity.Data.Configuration.Entities.ClientSecretEntity", b =>
                {
                    b.Property<string>("RealmId")
                        .HasColumnType("TEXT")
                        .HasColumnName("realm_id")
                        .UseCollation("BINARY");

                    b.Property<string>("ClientId")
                        .HasColumnType("TEXT")
                        .HasColumnName("client_id")
                        .UseCollation("BINARY");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ExpirationUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiration_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("RealmId", "ClientId", "Ordinal");

                    b.ToTable("client_secrets", (string)null);
                });

            modelBuilder.Entity("RoyalIdentity.Data.Configuration.Entities.ClientStringValueEntity", b =>
                {
                    b.Property<string>("RealmId")
                        .HasColumnType("TEXT")
                        .HasColumnName("realm_id")
                        .UseCollation("BINARY");

                    b.Property<string>("ClientId")
                        .HasColumnType("TEXT")
                        .HasColumnName("client_id")
                        .UseCollation("BINARY");

                    b.Property<string>("Kind")
                        .HasColumnType("TEXT")
                        .HasColumnName("kind")
                        .UseCollation("BINARY");

                    b.Property<string>("ComparisonKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("comparison_key")
                        .UseCollation("BINARY");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("RealmId", "ClientId", "Kind", "ComparisonKey");

                    b.ToTable("client_string_values", (string)null);
                });

            modelBuilder.Entity("RoyalIdentity.Data.Configuration.Entities.RealmEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .UseCollation("BINARY");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("domain")
                        .UseCollation("BINARY");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<bool>("Internal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("internal");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("options_json");

                    b.Property<int>("OptionsVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("options_version");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path")
                        .UseCollation("BINARY");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasDatabaseName("ux_realms_domain");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("ux_realms_path");

                    b.ToTable("realms", (string)null);
                });

            modelBuilder.Entity("RoyalIdentity.Data.Configuration.Entities.ServerOptionsEntity", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.Property<int>("PayloadVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("payload_version");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("server_options", null, t =>
                        {
                            t.HasCheckConstraint("ck_server_options_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("RoyalIdentity.Data.Configuration.Entities.SigningKeyEntity", b =>
                {
                    b.Property<string>("RealmId")
                        .HasColumnType("TEXT")
                        .HasColumnName("realm_id")
                        .UseCollation("BINARY");

                    b.Property<string>("KeyId")
                        .HasColumnType("TEXT")
                        .HasColumnName("key_id")
                        .UseCollation("BINARY");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<int>("Encoding")
                        .HasColumnType("INTEGER")
                        .HasColumnName("encoding");

                    b.Property<DateTime?>("ExpiresUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime?>("NotBeforeUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("not_before_utc");

                    b.Property<string>("ProtectedMaterial")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("protected_material");

                    b.Property<string>("ProtectorId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("protector_id");

                    b.Property<string>("SecurityAlgorithm")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("security_algorithm");

                    b.Property<int>("SerializationFormat")
                        .HasColumnType("INTEGER")
                        .HasColumnName("serialization_format");

                    b.HasKey("RealmId", "KeyId");

                    b.HasIndex("RealmId", "CreatedUtc")
                        .HasDatabaseName("ix_signing_keys_realm_created");

                    b.ToTable("signing_keys", (string)null);
                });

            modelBuilder.Entity("RoyalIdentity.Data.Configuration.Entities.ClientClaimEntity", b =>
                {
                    b.HasOne("RoyalIdentity.Data.Configuration.Entities.ClientEntity", null)
                        .WithMany()
                        .HasForeignKey("RealmId", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoyalIdentity.Data.Configuration.Entities.ClientEntity", b =>
                {
                    b.HasOne("RoyalIdentity.Data.Configuration.Entities.RealmEntity", null)
                        .WithMany()
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RoyalIdentity.Data.Configuration.Entities.ClientSecretEntity", b =>
                {
                    b.HasOne("RoyalIdentity.Data.Configuration.Entities.ClientEntity", null)
                        .WithMany()
                        .HasForeignKey("RealmId", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoyalIdentity.Data.Configuration.Entities.ClientStringValueEntity", b =>
                {
                    b.HasOne("RoyalIdentity.Data.Configuration.Entities.ClientEntity", null)
                        .WithMany()
                        .HasForeignKey("RealmId", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoyalIdentity.Data.Configuration.Entities.SigningKeyEntity", b =>
                {
                    b.HasOne("RoyalIdentity.Data.Configuration.Entities.RealmEntity", null)
                        .WithMany()
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
