<Project Sdk="Microsoft.NET.Sdk.Web">

	<ItemGroup>
		<ProjectReference Include="..\RoyalIdentity.Razor\RoyalIdentity.Razor.csproj" />
		<ProjectReference Include="..\RoyalIdentity.Storage.EntityFramework\RoyalIdentity.Storage.EntityFramework.csproj" />
		<ProjectReference Include="..\RoyalIdentity.Storage.EntityFramework.Sqlite\RoyalIdentity.Storage.EntityFramework.Sqlite.csproj" />
		<ProjectReference Include="..\RoyalIdentity.UserAccounts.Integration\RoyalIdentity.UserAccounts.Integration.csproj" />
		<ProjectReference Include="..\RoyalIdentity.UserAccounts.Sqlite\RoyalIdentity.UserAccounts.Sqlite.csproj" />
		<ProjectReference Include="..\RoyalIdentity.Migrations\RoyalIdentity.Migrations.csproj" />
		<ProjectReference Include="..\RoyalIdentity\RoyalIdentity.csproj" />
	</ItemGroup>

</Project>
