// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoyalIdentity.Storage.EntityFramework.PostgreSql;

#nullable disable

namespace RoyalIdentity.Storage.EntityFramework.PostgreSql.OperationalMigrations
{
    [DbContext(typeof(OperationalPostgreSqlDbContext))]
    partial class OperationalPostgreSqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoyalIdentity.Data.Operational.Entities.AuthorizeParametersEntity", b =>
                {
                    b.Property<string>("RealmId")
                        .HasColumnType("text")
                        .HasColumnName("realm_id")
                        .UseCollation("C");

                    b.Property<string>("HandleDigest")
                        .HasColumnType("text")
                        .HasColumnName("handle_digest")
                        .UseCollation("C");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<int>("PayloadVersion")
                        .HasColumnType("integer")
                        .HasColumnName("payload_version");

                    b.Property<string>("ProtectedPayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protected_payload");

                    b.HasKey("RealmId", "HandleDigest");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_authorize_parameters_expiration");

                    b.ToTable("authorize_parameters", "operation");
                });

            modelBuilder.Entity("RoyalIdentity.Data.Operational.Entities.ConsentEntity", b =>
                {
                    b.Property<string>("RealmId")
                        .HasColumnType("text")
                        .HasColumnName("realm_id")
                        .UseCollation("C");

                    b.Property<string>("SubjectId")
                        .HasColumnType("text")
                        .HasColumnName("subject_id")
                        .UseCollation("C");

                    b.Property<string>("ClientId")
                        .HasColumnType("text")
                        .HasColumnName("client_id")
                        .UseCollation("C");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<int>("PayloadVersion")
                        .HasColumnType("integer")
                        .HasColumnName("payload_version");

                    b.Property<string>("ProtectedPayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protected_payload");

                    b.HasKey("RealmId", "SubjectId", "ClientId");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_consents_expiration");

                    b.ToTable("consents", "operation");
                });

            modelBuilder.Entity("RoyalIdentity.Data.Operational.Entities.ProtocolArtifactEntity", b =>
                {
                    b.Property<string>("RealmId")
                        .HasColumnType("text")
                        .HasColumnName("realm_id")
                        .UseCollation("C");

                    b.Property<string>("ArtifactType")
                        .HasColumnType("text")
                        .HasColumnName("artifact_type")
                        .UseCollation("C");

                    b.Property<string>("LookupDigest")
                        .HasColumnType("text")
                        .HasColumnName("lookup_digest")
                        .UseCollation("C");

                    b.Property<int?>("AccessTokenType")
                        .HasColumnType("integer")
                        .HasColumnName("access_token_type");

                    b.Property<int?>("ClaimsMode")
                        .HasColumnType("integer")
                        .HasColumnName("claims_mode");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_id")
                        .UseCollation("C");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<int?>("PayloadVersion")
                        .HasColumnType("integer")
                        .HasColumnName("payload_version");

                    b.Property<string>("ProtectedPayload")
                        .HasColumnType("text")
                        .HasColumnName("protected_payload");

                    b.Property<string>("RedirectUri")
                        .HasColumnType("text")
                        .HasColumnName("redirect_uri")
                        .UseCollation("C");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id")
                        .UseCollation("C");

                    b.Property<int>("StateVersion")
                        .HasColumnType("integer")
                        .HasColumnName("state_version");

                    b.Property<string>("SubjectId")
                        .HasColumnType("text")
                        .HasColumnName("subject_id")
                        .UseCollation("C");

                    b.HasKey("RealmId", "ArtifactType", "LookupDigest");

                    b.HasIndex("ArtifactType", "ConsumedAtUtc")
                        .HasDatabaseName("ix_protocol_artifacts_consumed");

                    b.HasIndex("ArtifactType", "ExpiresAtUtc")
                        .HasDatabaseName("ix_protocol_artifacts_expiration");

                    b.HasIndex("RealmId", "SessionId")
                        .HasDatabaseName("ix_protocol_artifacts_session");

                    b.HasIndex("RealmId", "ArtifactType", "SubjectId", "ClientId")
                        .HasDatabaseName("ix_protocol_artifacts_subject");

                    b.ToTable("protocol_artifacts", "operation");
                });

            modelBuilder.Entity("RoyalIdentity.Data.Operational.Entities.UserSessionClientEntity", b =>
                {
                    b.Property<string>("RealmId")
                        .HasColumnType("text")
                        .HasColumnName("realm_id")
                        .UseCollation("C");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id")
                        .UseCollation("C");

                    b.Property<string>("ClientId")
                        .HasColumnType("text")
                        .HasColumnName("client_id")
                        .UseCollation("C");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at_utc");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.HasKey("RealmId", "SessionId", "ClientId");

                    b.ToTable("user_session_clients", "operation");
                });

            modelBuilder.Entity("RoyalIdentity.Data.Operational.Entities.UserSessionEntity", b =>
                {
                    b.Property<string>("RealmId")
                        .HasColumnType("text")
                        .HasColumnName("realm_id")
                        .UseCollation("C");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id")
                        .UseCollation("C");

                    b.Property<string>("AuthenticationMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authentication_method");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("IdentityProvider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_provider");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_id")
                        .UseCollation("C");

                    b.HasKey("RealmId", "SessionId");

                    b.HasIndex("EndedAtUtc")
                        .HasDatabaseName("ix_user_sessions_ended");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_user_sessions_expiration");

                    b.HasIndex("RealmId", "SubjectId", "IsActive")
                        .HasDatabaseName("ix_user_sessions_subject");

                    b.ToTable("user_sessions", "operation");
                });

            modelBuilder.Entity("RoyalIdentity.Data.Operational.Entities.UserSessionClientEntity", b =>
                {
                    b.HasOne("RoyalIdentity.Data.Operational.Entities.UserSessionEntity", null)
                        .WithMany()
                        .HasForeignKey("RealmId", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
